# auto generated file out of LuxandFaceSDK.h

### enum FSDK_VIDEOCOMPRESSIONTYPE
FSDK_MJPEG = 0

### enum FSDK_IMAGEMODE
FSDK_IMAGE_GRAYSCALE_8BIT = 0
FSDK_IMAGE_COLOR_24BIT = 1
FSDK_IMAGE_COLOR_32BIT = 2

### Error codes
FSDKE_OK = 0
FSDKE_FAILED = -1
FSDKE_NOT_ACTIVATED = -2
FSDKE_OUT_OF_MEMORY = -3
FSDKE_INVALID_ARGUMENT = -4
FSDKE_IO_ERROR = -5
FSDKE_IMAGE_TOO_SMALL = -6
FSDKE_FACE_NOT_FOUND = -7
FSDKE_INSUFFICIENT_BUFFER_SIZE = -8
FSDKE_UNSUPPORTED_IMAGE_EXTENSION = -9
FSDKE_CANNOT_OPEN_FILE = -10
FSDKE_CANNOT_CREATE_FILE = -11
FSDKE_BAD_FILE_FORMAT = -12
FSDKE_FILE_NOT_FOUND = -13
FSDKE_CONNECTION_CLOSED = -14
FSDKE_CONNECTION_FAILED = -15
FSDKE_IP_INIT_FAILED = -16
FSDKE_NEED_SERVER_ACTIVATION = -17
FSDKE_ID_NOT_FOUND = -18
FSDKE_ATTRIBUTE_NOT_DETECTED = -19
FSDKE_INSUFFICIENT_TRACKER_MEMORY_LIMIT = -20
FSDKE_UNKNOWN_ATTRIBUTE = -21
FSDKE_UNSUPPORTED_FILE_VERSION = -22
FSDKE_SYNTAX_ERROR = -23
FSDKE_PARAMETER_NOT_FOUND = -24
FSDKE_INVALID_TEMPLATE = -25
FSDKE_UNSUPPORTED_TEMPLATE_VERSION = -26
FSDKE_CAMERA_INDEX_DOES_NOT_EXIST = -27
FSDKE_PLATFORM_NOT_LICENSED = -28

### Facial feature count
FSDK_FACIAL_FEATURE_COUNT = 70

### Facial features
FSDKP_LEFT_EYE = 0
FSDKP_RIGHT_EYE = 1
FSDKP_LEFT_EYE_INNER_CORNER = 24
FSDKP_LEFT_EYE_OUTER_CORNER = 23
FSDKP_LEFT_EYE_LOWER_LINE1 = 38
FSDKP_LEFT_EYE_LOWER_LINE2 = 27
FSDKP_LEFT_EYE_LOWER_LINE3 = 37
FSDKP_LEFT_EYE_UPPER_LINE1 = 35
FSDKP_LEFT_EYE_UPPER_LINE2 = 28
FSDKP_LEFT_EYE_UPPER_LINE3 = 36
FSDKP_LEFT_EYE_LEFT_IRIS_CORNER = 29
FSDKP_LEFT_EYE_RIGHT_IRIS_CORNER = 30
FSDKP_RIGHT_EYE_INNER_CORNER = 25
FSDKP_RIGHT_EYE_OUTER_CORNER = 26
FSDKP_RIGHT_EYE_LOWER_LINE1 = 41
FSDKP_RIGHT_EYE_LOWER_LINE2 = 31
FSDKP_RIGHT_EYE_LOWER_LINE3 = 42
FSDKP_RIGHT_EYE_UPPER_LINE1 = 40
FSDKP_RIGHT_EYE_UPPER_LINE2 = 32
FSDKP_RIGHT_EYE_UPPER_LINE3 = 39
FSDKP_RIGHT_EYE_LEFT_IRIS_CORNER = 33
FSDKP_RIGHT_EYE_RIGHT_IRIS_CORNER = 34
FSDKP_LEFT_EYEBROW_INNER_CORNER = 13
FSDKP_LEFT_EYEBROW_MIDDLE = 16
FSDKP_LEFT_EYEBROW_MIDDLE_LEFT = 18
FSDKP_LEFT_EYEBROW_MIDDLE_RIGHT = 19
FSDKP_LEFT_EYEBROW_OUTER_CORNER = 12
FSDKP_RIGHT_EYEBROW_INNER_CORNER = 14
FSDKP_RIGHT_EYEBROW_MIDDLE = 17
FSDKP_RIGHT_EYEBROW_MIDDLE_LEFT = 20
FSDKP_RIGHT_EYEBROW_MIDDLE_RIGHT = 21
FSDKP_RIGHT_EYEBROW_OUTER_CORNER = 15
FSDKP_NOSE_TIP = 2
FSDKP_NOSE_BOTTOM = 49
FSDKP_NOSE_BRIDGE = 22
FSDKP_NOSE_LEFT_WING = 43
FSDKP_NOSE_LEFT_WING_OUTER = 45
FSDKP_NOSE_LEFT_WING_LOWER = 47
FSDKP_NOSE_RIGHT_WING = 44
FSDKP_NOSE_RIGHT_WING_OUTER = 46
FSDKP_NOSE_RIGHT_WING_LOWER = 48
FSDKP_MOUTH_RIGHT_CORNER = 3
FSDKP_MOUTH_LEFT_CORNER = 4
FSDKP_MOUTH_TOP = 54
FSDKP_MOUTH_TOP_INNER = 61
FSDKP_MOUTH_BOTTOM = 55
FSDKP_MOUTH_BOTTOM_INNER = 64
FSDKP_MOUTH_LEFT_TOP = 56
FSDKP_MOUTH_LEFT_TOP_INNER = 60
FSDKP_MOUTH_RIGHT_TOP = 57
FSDKP_MOUTH_RIGHT_TOP_INNER = 62
FSDKP_MOUTH_LEFT_BOTTOM = 58
FSDKP_MOUTH_LEFT_BOTTOM_INNER = 63
FSDKP_MOUTH_RIGHT_BOTTOM = 59
FSDKP_MOUTH_RIGHT_BOTTOM_INNER = 65
FSDKP_NASOLABIAL_FOLD_LEFT_UPPER = 50
FSDKP_NASOLABIAL_FOLD_LEFT_LOWER = 52
FSDKP_NASOLABIAL_FOLD_RIGHT_UPPER = 51
FSDKP_NASOLABIAL_FOLD_RIGHT_LOWER = 53
FSDKP_CHIN_BOTTOM = 11
FSDKP_CHIN_LEFT = 9
FSDKP_CHIN_RIGHT = 10
FSDKP_FACE_CONTOUR1 = 7
FSDKP_FACE_CONTOUR2 = 5
FSDKP_FACE_CONTOUR12 = 6
FSDKP_FACE_CONTOUR13 = 8
FSDKP_FACE_CONTOUR14 = 66
FSDKP_FACE_CONTOUR15 = 67
FSDKP_FACE_CONTOUR16 = 68
FSDKP_FACE_CONTOUR17 = 69

### FSDK_FaceTemplate size
FSDK_FACE_TEMPLATE_SIZE = 1024 + 4*4

### Combinations

FSDKP_LEFT_EYE_SET =  (FSDKP_LEFT_EYE, FSDKP_LEFT_EYE_INNER_CORNER, FSDKP_LEFT_EYE_OUTER_CORNER,
	FSDKP_LEFT_EYE_LOWER_LINE1, FSDKP_LEFT_EYE_LOWER_LINE2, FSDKP_LEFT_EYE_LOWER_LINE3,
	FSDKP_LEFT_EYE_UPPER_LINE1, FSDKP_LEFT_EYE_UPPER_LINE2, FSDKP_LEFT_EYE_UPPER_LINE3,
	FSDKP_LEFT_EYE_RIGHT_IRIS_CORNER, FSDKP_LEFT_EYE_LEFT_IRIS_CORNER)

FSDKP_RIGHT_EYE_SET =  (FSDKP_RIGHT_EYE, FSDKP_RIGHT_EYE_INNER_CORNER, FSDKP_RIGHT_EYE_OUTER_CORNER,
	FSDKP_RIGHT_EYE_LOWER_LINE1, FSDKP_RIGHT_EYE_LOWER_LINE2, FSDKP_RIGHT_EYE_LOWER_LINE3,
	FSDKP_RIGHT_EYE_UPPER_LINE1, FSDKP_RIGHT_EYE_UPPER_LINE2, FSDKP_RIGHT_EYE_UPPER_LINE3,
	FSDKP_RIGHT_EYE_LEFT_IRIS_CORNER, FSDKP_RIGHT_EYE_RIGHT_IRIS_CORNER)
